# Generated by Django 5.2.17 on 2026-09-23 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_path', models.CharField(max_length=500)),
                ('page_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_type', models.CharField(choices=[('text', 'text'), ('table', 'table'), ('figure', 'figure')], max_length=10)),
                ('page_number', models.IntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('content_text', models.TextField()),
                ('content_markdown', models.TextField(blank=True, default='')),
                ('chroma_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ingestion.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'chunk_type'], name='ingestion_c_documen_f12743_idx')],
            },
        ),
    ]
