# Generated by Django 5.2.17 on 2026-09-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20)),
                ('key_alias', models.CharField(max_length=50, unique=True)),
                ('api_key', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('rpm_limit', models.IntegerField(default=30)),
                ('rpd_limit', models.IntegerField(default=1000)),
                ('tpm_limit', models.IntegerField(default=100000)),
                ('requests_this_minute', models.IntegerField(default=0)),
                ('requests_today', models.IntegerField(default=0)),
                ('tokens_this_minute', models.IntegerField(default=0)),
                ('last_reset_minute', models.DateTimeField(blank=True, null=True)),
                ('last_reset_day', models.DateTimeField(blank=True, null=True)),
                ('last_request_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
